### ISSUE TITLE
поч читы не работают

### ISSUE THREAD

**Issue by Luminate-D** [Assasans/protanki-server#121]
как вы коммьюинти развивать будете без читов???

**Comment by Undixd** [comment]
ГЕНИЙЙЙ МЫСЛИИИИИИИИИИИИИИИИИИ ПРОСТО АХАХАХ

**Comment by Undixd** [comment]
Асик обьясни этому гению чё за хуйню он высрал

**Comment by kuraysdev** [comment]
Еб вашуж мать про читы забыли. Спасибо пожалуйста добавим завтра в четверг
