### ISSUE TITLE
Do you wanna create server for TO official?

### ISSUE THREAD

**Issue by AntonSibgatulin** [Assasans/protanki-server#124]
Hey @Assasans i saw your code of protanki-server.That's cool.Do you wanna try to create server for html5 versioin tanki online on kotlin/java myabe something on rust??? For official tanki online https://tankionline.com/play/ . We can download their client from someone test server - https://test.tankionline.com/ .Im already tries do this 2 years ago but i couldnt cuz i cant understand their protocol but i could run client from my server .I think i already lost all of mine code for it but maybe and not but i have a lot of screen with it. Maybe you already understand it or we can do it together?

I think it not will be problem for us.
email: 8987920@mail.ru
telegram: 89879203004
facebook: facebook.com/anton.sibgatulin.7

**Comment by MisterAllowne** [comment]
Let's say I managed to connect the server how do I access the game (I'm a beginner)

**Comment by MisterAllowne** [comment]
I think you misunderstood, I started the server that Assasans made the repository available, but I don't understand how I enter the game now, if it's through the browser or some executable

**Comment by TheEntropyShard** [comment]
You can use my [PTLauncher](https://github.com/TheEntropyShard/PTLauncher) or [this client launcher](https://github.com/protanki-re/client-launcher)

**Comment by kuraysdev** [comment]
We are currently working on the Araumi TO project. For more information: https://araumi.org.
