### ISSUE TITLE
damage is bugged

### ISSUE THREAD

**Issue by FatalDiscovery** [Assasans/protanki-server#128]
all weapon damage is fixed to like 100, i would think that damage wasnt implemented yet, but thunder self damage works properly

**Comment by FatalDiscovery** [comment]
isnt that like 0.0001$? 👽

**Comment by C6OI** [comment]
> isnt that like 0.0001$? 👽

1500 rubles

**Comment by kuraysdev** [comment]
This project is NOT developed anymore. You will NOT get any support. Henceforth, you are on your own.

Assasans now working at https://araumi.org
Issue closed

**Comment by C6OI** [comment]
> This project is NOT developed anymore. You will NOT get any support. Henceforth, you are on your own.
> 
> Assasans now working at https://araumi.org Issue closed

just 1500 rubles

**Comment by FatalDiscovery** [comment]
> This project is NOT developed anymore. You will NOT get any support. Henceforth, you are on your own.
> 
> Assasans now working at https://araumi.org Issue closed

ok bro no need to get so mad
