### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by PTanks** [Assasans/protanki-server#17]
Может добавить карт можно еще?
Там нужен айди и крч пж сделайте.

**Comment by kuraysdev** [comment]
Посмотрим по ходу дела. Сейчас в целях реализация основного функционала. Позже займемся добавлением карт, либо если будет свободное время.

**Comment by Longren1337** [comment]
Можешь в кратце объяснить откуда брать данные о освещении? Айди узнать легко, а какая именно это карта - сложновато(

**Comment by Assasans** [comment]
Сервер их передаёт при входе в битву (`init_battle_model`), подробнее на скриншоте.
![изображение](https://user-images.githubusercontent.com/39215393/161472549-c77e4991-a527-455d-8d03-ecae9395eff9.png)

Патч для сохранения пакетов, который я использую: [logall.txt](https://github.com/Assasans/protanki-server/files/8406652/logall.txt).

**Comment by Longren1337** [comment]
Большое спасибо)

**Comment by PTanks** [comment]
Прост хотел сказать что ты красавец

**Comment by Longren1337** [comment]
> Сервер их передаёт при входе в битву (`init_battle_model`), подробнее на скриншоте. ![изображение](https://user-images.githubusercontent.com/39215393/161472549-c77e4991-a527-455d-8d03-ecae9395eff9.png)
> 
> Патч для сохранения пакетов, который я использую: [logall.txt](https://github.com/Assasans/protanki-server/files/8406652/logall.txt).

В итоге получилось добавить, благодарю
