### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by Assasans** [Assasans/protanki-server#19]
- [x] `2042` (summer, day)
- [x] `2042` (winter, day)
- [x] `abyss` (summer, day)
- [x] `abyss` (winter, day)
- [x] `aleksandrovsk` (summer, day)
- [x] `aleksandrovsk` (winter, day)
- [x] `aleksandrovsk` (summer, night)
- [x] `arena` (summer, day)
- [x] `arena` (winter, day)
- [x] `atra` (summer, day)
- [x] `atra` (winter, day)
- [x] `barda` (summer, day)
- [x] `barda` (winter, day)
- [x] `barda` (summer, night)
- [x] `berlin` (summer, day)
- [x] `berlin` (winter, day)
- [x] `bobruisk` (summer, day)
- [x] `bobruisk` (winter, day)
- [x] `boombox` (summer, day)
- [x] `boombox` (winter, day)
- [x] `brest` (summer, day)
- [x] `brest` (winter, day)
- [x] `bridges` (summer, day)
- [x] `bridges` (winter, day)
- [x] `camp` (summer, day)
- [x] `camp` (winter, day)
- [x] `canyon` (summer, day)
- [x] `canyon` (winter, day)
- [x] `chornobyl` (summer, day)
- [x] `chornobyl` (winter, day)
- [x] `combe` (summer, day)
- [x] `combe` (winter, day)
- [x] `courage` (summer, day)
- [x] `courage` (winter, day)
- [x] `cross` (summer, day)
- [x] `cross` (winter, day)
- [x] `deathtrack` (summer, day)
- [x] `deathtrack` (winter, day)
- [x] `deck9` (summer, day)
- [x] `deck9` (winter, day)
- [x] `desert` (summer, day)
- [x] `desert` (winter, day)
- [x] `dualiti` (summer, day)
- [x] `dualiti` (winter, day)
- [x] `duel` (summer, day)
- [x] `duel` (winter, day)
- [x] `dusseldorf` (summer, day)
- [x] `dusseldorf` (winter, day)
- [x] `edinburgh` (summer, day)
- [x] `edinburgh` (winter, day)
- [x] `esplanade` (summer, day)
- [x] `esplanade` (winter, day)
- [x] `factory` (summer, day)
- [x] `farm` (summer, day)
- [x] `farm` (winter, day)
- [x] `forest` (summer, day)
- [x] `forest` (winter, day)
- [x] `fortknox` (summer, day)
- [x] `fortknox` (winter, day)
- [x] `future` (summer, day)
- [x] `future` (summer, night)
- [x] `garder` (summer, day)
- [x] `garder` (winter, day)
- [x] `gravity` (summer, day)
- [x] `gravity` (winter, day)
- [x] `gubakha` (summer, day)
- [x] `gubakha` (winter, day)
- [x] `highland` (summer, day)
- [x] `highland` (winter, day)
- [x] `highway` (summer, day)
- [x] `highway` (winter, day)
- [x] `hill` (summer, day)
- [x] `hill` (winter, day)
- [x] `industrial_zone` (summer, day)
- [x] `industrial_zone` (winter, day)
- [x] `iran` (summer, day)
- [x] `iran` (winter, day)
- [x] `island` (summer, day)
- [x] `island` (winter, day)
- [x] `kolhoz` (summer, day)
- [x] `kolhoz` (winter, day)
- [x] `kungur` (summer, day)
- [x] `kungur` (winter, day)
- [x] `losttemple` (summer, day)
- [x] `losttemple` (winter, day)
- [x] `madness_space` (space)
- [x] `madness_old` (space)
- [x] `magadan` (summer, day)
- [x] `magadan` (winter, day)
- [x] `magistral` (summer, day)
- [x] `magistral` (winter, day)
- [x] `massacre` (summer, day)
- [x] `massacre` (winter, day)
- [x] `molotov` (summer, day)
- [x] `molotov` (winter, day)
- [x] `montecarlo` (summer, day)
- [x] `montecarlo` (winter, day)
- [x] `noise` (summer, day)
- [x] `noise` (winter, day)
- [x] `novel` (summer, day)
- [x] `novel` (winter, day)
- [x] `opposition` (summer, day)
- [x] `opposition` (winter, day)
- [x] `osa` (summer, day)
- [x] `osa` (winter, day)
- [x] `parma` (summer, day)
- [x] `parma` (winter, day)
- [x] `pass` (summer, day)
- [x] `pass` (winter, day)
- [x] `pingpong` (summer, day)
- [x] `pingpong` (winter, day)
- [x] `platform` (space)
- [x] `polygon` (summer, day)
- [x] `polygon` (winter, day)
- [x] `polygon` (summer, night)
- [x] `redalert` (summer, day)
- [x] `redalert` (winter, day)
- [x] `rift` (summer, day)
- [x] `rift` (winter, day)
- [x] `rio` (summer, day)
- [x] `rio` (summer, night)
- [x] `sandal` (summer, day)
- [x] `sandal` (winter, day)
- [x] `sandbox` (summer, day)
- [x] `sandbox` (winter, day)
- [x] `sandbox` (summer, night)
- [x] `scope` (summer, day)
- [x] `scope` (winter, day)
- [x] `serpuhov` (summer, day)
- [x] `serpuhov` (winter, day)
- [x] `shortbridge` (summer, day)
- [x] `shortbridge` (winter, day)
- [x] `siege` (summer, day)
- [x] `siege` (winter, day)
- [x] `silence` (summer, day)
- [x] `silence` (winter, day)
- [x] `silence` (summer, night)
- [x] `silence_moon` (space)
- [x] `skylark` (summer, day)
- [x] `skylark` (winter, day)
- [x] `skyscrapers` (summer, day)
- [x] `skyscrapers` (space)
- [x] `solikamsk` (summer, day)
- [x] `solikamsk` (winter, day)
- [x] `stadium` (summer, day)
- [x] `stadium` (winter, day)
- [x] `stadium` (summer, night)
- [x] `station` (summer, day)
- [x] `station` (winter, day)
- [x] `subway` (summer, day)
- [x] `subway` (winter, day)
- [x] `tribute` (summer, day)
- [x] `tribute` (winter, day)
- [x] `valley` (summer, day)
- [x] `valley` (winter, day)
- [x] `wave` (summer, day)
- [x] `wave` (winter, day)
- [x] `wolfenstein` (summer, day)
- [x] `wolfenstein` (winter, day)
- [x] `zone` (summer, day)
- [x] `zone` (winter, day)

**Comment by Longren1337** [comment]
Chernobyl has been removed in PT, sad
