### ISSUE TITLE
(help wanted) Как добавлять карты

### ISSUE THREAD

**Issue by PTanks** [Assasans/protanki-server#20]
Можете рассказать как самому можно разобратся как добавлять карты? Я знаю что вы сами потихоньку все доробатывайте и делаете, но мне интерессно как оно так делается.
Я как понял они уже есть в клиенте, но надо найти айди карты через дебаг (мне друг подсказал) который находится на сервере пт и нужны еще json файлы где спавн точки и тд, но я хз как это найти и все это крч

Кста посмотрел на код хотя я не шарю как пишутся сервера, могу сказать что вы полные красавцы и делаете а*уенную вещь покачто!

**Comment by Assasans** [comment]
Я сделал скрипт для генерации конфигурации карты из пакетов входа в битву: https://github.com/Assasans/protanki-utils.
Точки спавна, флаги и т.д. лежат в XML файле карты, ID и версия которого отправляется в третьем пакете `load_resources`.

**Comment by Longren1337** [comment]
> Я сделал скрипт для генерации конфигурации карты из пакетов входа в битву: https://github.com/Assasans/protanki-utils. Точки спавна, флаги и т.д. лежат в XML файле карты, ID и версия которого отправляется в третьем пакете `load_resources`.

Это очень круто

**Comment by PTanks** [comment]
> Я сделал скрипт для генерации конфигурации карты из пакетов входа в битву: https://github.com/Assasans/protanki-utils. Точки спавна, флаги и т.д. лежат в XML файле карты, ID и версия которого отправляется в третьем пакете `load_resources`.

Я тебя люблю

**Comment by C6OI** [comment]
> Я сделал скрипт для генерации конфигурации карты из пакетов входа в битву: https://github.com/Assasans/protanki-utils.
> Точки спавна, флаги и т.д. лежат в XML файле карты, ID и версия которого отправляется в третьем пакете `load_resources`.

Го сосаться
