### ISSUE TITLE
Running the server on Windows

### ISSUE THREAD

**Issue by Colly001** [Assasans/protanki-server#3]
i made a new .bat file with the command ```java jp.assasans.protanki.server.Server ProTankiServer-0.1.0.jar``` it doesn`t work.
What should i put?

**Comment by Assasans** [comment]
Main class is set in the JAR automatically, you can just use `java -jar ProTankiServer-0.1.0.jar`.
If you want to specify class manually: `java -cp ProTankiServer-0.1.0.jar jp.assasans.protanki.server.MainKt`
