### ISSUE TITLE
The server does not start

### ISSUE THREAD

**Issue by GScript-android** [Assasans/protanki-server#56]
With the latest update, the server stopped loading, compilation is successful, but server startup is not.
![2022-04-11_18-56-43](https://user-images.githubusercontent.com/67222379/162756435-589f8ed6-531d-4b3e-88ce-4fe255b30631.png)
![2022-04-11_18-49-34](https://user-images.githubusercontent.com/67222379/162756442-b3c8d6c3-8858-4c63-a24a-669800014fd8.png)

**Comment by Assasans** [comment]
Fixed in 1beedd1

**Comment by GScript-android** [comment]
Yes, thanks, it worked, but the "bug" appeared again, it is impossible to create a map
https://disk.yandex.ru/d/RoAoZWoASweGsQ

**Comment by GScript-android** [comment]
Yes, thanks, it worked, but the "bug" appeared again, it is impossible to create a map
https://disk.yandex.ru/d/RoAoZWoASweGsQ

**Comment by Assasans** [comment]
Fixed in 2e06aab

**Comment by gravayo3epo** [comment]
Пацаны, как и когда можно зайти на сервер?

**Comment by keneshindev** [comment]
> Пацаны, как и когда можно зайти на сервер?

Можно захостить сервер самому :)

**Comment by kuraysdev** [comment]
> Пацаны, как и когда можно зайти на сервер?

Не думаю что мы собираемся поднимать хост. Если хочешь можешь запустить сам и потестить. в docs/building.md находится информация по сборке сервера.

**Comment by GScript-android** [comment]
> 

Это да, но локальный сервер никто не отменял 😉
