### ISSUE TITLE
Не появляется окно создания битвы

### ISSUE THREAD

**Issue by efsfssf** [Assasans/protanki-server#77]
Шаги воспроизведения:

1. Запускаем сервер
2. Заходим в игру
3. Создаем карту "Лунная тишина" выходим из игры
4. Заходим в игру и пытаемся создать битву

Даже перезапуск сервера не помогает

**Comment by Assasans** [comment]
Смог повторить

**Comment by Assasans** [comment]
Исправлено в 654fa9b
