### ISSUE TITLE
Не загружает в битву со спектатора.

### ISSUE THREAD

**Issue by Longren1337** [Assasans/protanki-server#84]
Случай, когда режим спектатора загружается:
1. Запуск сервера.
2. Человек, который заходит первый на сервер, может создать битву и зайти в неё со спека.
3. После этого остальные люди могут заходить в битву.

Но, если на карте уже кто-то был/есть, со спектатора невозможно зайти.

**Comment by Assasans** [comment]
Исправил (надеюсь) в d2f4409 и 374d3bf

**Comment by Longren1337** [comment]
Буду тестить

**Comment by Longren1337** [comment]
Сам сейчас пытался сделать фикс, но всё равно не всегда загружало

**Comment by Longren1337** [comment]
Попробую из коммита загрузить

**Comment by Longren1337** [comment]
Теперь стало всё окей, могу закрывать ветку.
