### ISSUE TITLE
гг всему чёли?

### ISSUE THREAD

**Issue by Kleins0** [Assasans/protanki-server#90]
![image](https://user-images.githubusercontent.com/82320282/164966864-add6eaa2-e80a-4521-a74c-f1f18a5b1532.png)
![image](https://user-images.githubusercontent.com/82320282/164966872-514998c8-fc0c-43e9-8291-a287c5965df7.png)

**Comment by Assasans** [comment]
Разработчики удалили 6 версию ресурса золотого ящика, исправлено в 290421a.

> ![](https://user-images.githubusercontent.com/82320282/164966864-add6eaa2-e80a-4521-a74c-f1f18a5b1532.png)

О каком SWF файле идет речь? У меня `library.swf` открывается.

**Comment by Kleins0** [comment]
Открылось свф, просто фигня какаето, спс за фикс

**Comment by Kleins0** [comment]
![image](https://user-images.githubusercontent.com/82320282/164969050-bc8c5b14-6e0a-4fd1-b5d0-ef8a81492207.png)
Где краски xd

**Comment by Kleins0** [comment]
![image](https://user-images.githubusercontent.com/82320282/164969107-797aab6c-0bc2-4d49-91c6-02f302d03d92.png)
